version: 1.0.{build}

branches:
  only:
    - master
environment:
  nodejs_version: "6"

install:
  - npm install
  - npm install elm -g 
  - npm install webpack -g 
  - elm-package install --yes

build_script:
  - webpack --config webpack.config.prod.js

on_success:
  - cd dist
  - git add -A
  - git commit -m 'Relase'
  - git remote add deploy ssh://root@46.101.41.13/projects/sensor-frontend

